### PR TITLE
Time Signals and AutoMove (#6)

### LINKED ISSUE #26: Update LICENSE

### LINKED ISSUE #29: Implement count-up feature and add onUpdate callback to timer.
https://github.com/PrepTimer/PrepTime/blob/60602c4c390c2e16d26bec5e3da56ecd5c0bf706/lib/models/countdown_timer.dart#L1-L1

### PR DESCRIPTION
**Pull request by notjustinshaw**
# THIS IS A NIGHTMARE
Note to self: Do smaller branches in the future.
LGTM

### CODE REVIEW

**Comment by sorenrood** [comment]
lol

**Comment by justinalexandershaw** [comment]
It's been a struggle @sorenrood (see https://github.com/PrepTimer/PrepTime/pull/33/commits/fde3757c7cae2b5cfa08f0edec25aaf6290ed2c0)

**Comment by sorenrood** [comment]
> It's been a struggle @sorenrood (see [fde3757](https://github.com/PrepTimer/PrepTime/commit/fde3757c7cae2b5cfa08f0edec25aaf6290ed2c0))

Oh my gosh 😆. I feel that. Sometimes you just can't think of a good commit message.

**Comment by sorenrood** [comment]
:eyes:

**Comment by justinalexandershaw** [comment]
69 commits? Nice.
100% coverage? Nice.
LGTM.

**Comment by justinalexandershaw** [comment]
Screen Shot 2021-01-01 at 2 23 04 AM

**Comment by sorenrood** [comment]
> 69 commits? Nice.
> 100% coverage? Nice.
> LGTM.

lol

**Pull request merged**
